# Generated by Django 4.0.1 on 2022-02-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='ccccc',
            field=models.CharField(default=0, max_length=10, verbose_name='상품 가격2'),
            preserve_default=False,
        ),
    ]
