# Generated by Django 4.0.1 on 2022-02-14 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_photo_ccccc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='ccccc',
        ),
    ]
