# Generated by Django 3.1.3 on 2022-02-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20220202_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='season',
            field=models.CharField(default=1, max_length=20, verbose_name='상품 시즌'),
            preserve_default=False,
        ),
    ]
