# Generated by Django 4.0.1 on 2022-02-14 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_rename_money_photo_money2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='money2',
            new_name='money',
        ),
    ]
