# Generated by Django 3.1.3 on 2022-02-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_photo_stock_alter_album_id_alter_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='stock',
            field=models.IntegerField(verbose_name='재고 수량'),
        ),
    ]
