# Generated by Django 4.0.1 on 2022-02-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_rename_money2_photo_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.CharField(default=0, max_length=250)),
            ],
        ),
    ]
