# Generated by Django 4.0.1 on 2022-02-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='price',
            field=models.CharField(default=0, max_length=250),
        ),
    ]
