# Generated by Django 4.0.1 on 2022-02-14 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0010_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='owner',
        ),
    ]
