# Generated by Django 3.1.3 on 2022-03-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='phone'),
        ),
    ]
