# Generated by Django 3.1.3 on 2022-03-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender2',
            field=models.CharField(max_length=5, null=True, verbose_name='gender2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.TextField(max_length=11, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='realname',
            field=models.CharField(max_length=20, null=True, verbose_name='realname'),
        ),
    ]
