# Generated by Django 3.1.3 on 2022-03-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
