# Generated by Django 3.1.3 on 2022-03-21 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_auto_20220321_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.photo')),
            ],
        ),
    ]
