# Generated by Django 3.1.3 on 2022-03-22 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
