# Generated by Django 3.1.3 on 2022-03-30 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insta', '0005_auto_20220330_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='voter',
            field=models.ManyToManyField(null=True, related_name='voter_photo', to=settings.AUTH_USER_MODEL),
        ),
    ]
