# Generated by Django 3.1.3 on 2022-02-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_photo_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.AddField(
            model_name='photo',
            name='Material',
            field=models.TextField(blank=True, verbose_name='소재'),
        ),
        migrations.AddField(
            model_name='photo',
            name='size',
            field=models.TextField(blank=True, verbose_name='사이즈'),
        ),
        migrations.AddField(
            model_name='photo',
            name='style',
            field=models.TextField(blank=True, verbose_name='스타일'),
        ),
    ]
